export const userData = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "555-1234",
    username: "johndoe",
    street: "123 Main St",
    city: "New York",
    companyName: "Doe Enterprises",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "555-5678",
    username: "janesmith",
    street: "456 Elm St",
    city: "Los Angeles",
    companyName: "Smith & Co.",
  },
  {
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    phone: "555-8765",
    username: "mjohnson",
    street: "789 Oak St",
    city: "Chicago",
    companyName: "Johnson Solutions",
  },
  {
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "555-4321",
    username: "emilyd",
    street: "101 Maple Ave",
    city: "Houston",
    companyName: "Davis Designs",
  },
  {
    name: "Daniel Brown",
    email: "daniel.brown@example.com",
    phone: "555-3456",
    username: "danbrown",
    street: "202 Pine St",
    city: "Phoenix",
    companyName: "Brown Innovations",
  },
  {
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    phone: "555-6543",
    username: "swilson",
    street: "303 Birch Ln",
    city: "Philadelphia",
    companyName: "Wilson Works",
  },
  {
    name: "David Miller",
    email: "david.miller@example.com",
    phone: "555-7890",
    username: "dmiller",
    street: "404 Cedar St",
    city: "San Antonio",
    companyName: "Miller Machines",
  },
  {
    name: "Ava Taylor",
    email: "ava.taylor@example.com",
    phone: "555-0987",
    username: "avat",
    street: "505 Cherry Rd",
    city: "San Diego",
    companyName: "Taylor Technologies",
  },
  {
    name: "Christopher Anderson",
    email: "chris.anderson@example.com",
    phone: "555-7654",
    username: "canderson",
    street: "606 Spruce Ave",
    city: "Dallas",
    companyName: "Anderson Industries",
  },
  {
    name: "Olivia Thomas",
    email: "olivia.thomas@example.com",
    phone: "555-4320",
    username: "oliviath",
    street: "707 Aspen St",
    city: "San Jose",
    companyName: "Thomas Co.",
  },
  {
    name: "James Lee",
    email: "james.lee@example.com",
    phone: "555-3210",
    username: "jamesl",
    street: "808 Poplar Blvd",
    city: "Austin",
    companyName: "Lee Logistics",
  },
  {
    name: "Isabella Harris",
    email: "isabella.harris@example.com",
    phone: "555-2345",
    username: "iharris",
    street: "909 Redwood Dr",
    city: "Jacksonville",
    companyName: "Harris Holdings",
  },
  {
    name: "Benjamin Martin",
    email: "benjamin.martin@example.com",
    phone: "555-5670",
    username: "benmartin",
    street: "1001 Cypress St",
    city: "Fort Worth",
    companyName: "Martin Management",
  },
  {
    name: "Mia Clark",
    email: "mia.clark@example.com",
    phone: "555-6789",
    username: "miaclark",
    street: "1102 Fir Ave",
    city: "Columbus",
    companyName: "Clark Corp",
  },
  {
    name: "Matthew Robinson",
    email: "matthew.robinson@example.com",
    phone: "555-8901",
    username: "mattrob",
    street: "1203 Willow Way",
    city: "Charlotte",
    companyName: "Robinson Real Estate",
  }
];
